# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         lib-http
version:      0.01
version_from: lib/lib/http.pm
installdirs:  site
requires:
    Compress::Zlib:                1.2
    LibZip:                        0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
